name: CD - Deploy & DAST

on:
  workflow_call:

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:

  # ============================================================
  # GATE 8: DEPLOY
  # ============================================================
  deploy:
    name: Deploy to EC2 via SSH
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          #----------------------
          envs: AWS_REGION,AWS_ACCOUNT_ID,ECR_REPOSITORY,IMAGE_TAG
          script: |
            # Registry URL ko build karein
            ECR_REGISTRY="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
            
            # 1. Login to ECR
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

            cd ~/bankapp

            # 2. Get Secrets and create .env
            aws secretsmanager get-secret-value --secret-id bankapp/prod-secrets --query SecretString --output text > secrets.json

            echo "DB_HOST=$(jq -r .DB_HOST secrets.json)" > .env
            echo "DB_PORT=$(jq -r .DB_PORT secrets.json)" >> .env
            echo "DB_NAME=$(jq -r .DB_NAME secrets.json)" >> .env
            echo "DB_USER=$(jq -r .DB_USER secrets.json)" >> .env
            echo "DB_PASSWORD=$(jq -r .DB_PASSWORD secrets.json)" >> .env
            echo "OLLAMA_URL=http://172.17.0.1:11434" >> .env
            echo "OLLAMA_MODEL=tinyllama" >> .env
            
            # Docker variables mapping
            echo "ECR_REGISTRY=$ECR_REGISTRY" >> .env
            echo "ECR_REPOSITORY=$ECR_REPOSITORY" >> .env
            echo "IMAGE_TAG=$IMAGE_TAG" >> .env

            rm secrets.json

            # 3. Pull and Deploy
            docker compose -f app-tier.yml pull
            docker compose -f app-tier.yml up -d
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: "781970762520"
          ECR_REPOSITORY: "banking-app-devsecops-k8s"
          IMAGE_TAG: ${{ github.sha }}


  # ============================================================
  # GATE 9: DAST - Dynamic Application Security Testing
  # ============================================================
  dast:
    name: DAST - OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        continue-on-error: true  # Workaround for ZAP's internal artifact upload bug
        with:
          target: 'http://${{ secrets.EC2_HOST }}:8080'
          artifact_name: zapreport
          fail_action: false
          allow_issue_writing: false

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-dast-report
          path: report_html.html